### ISSUE TITLE
 /etc/init.d/douane cannot start on OpenSuse Leap 42.3

### ISSUE THREAD

**Issue by roker** [Douane/douane-daemon#10]
(author: thank you for creating this, actually i believe a better way would be to hook ELF calls using system wide preload and extend it to not only filter connections but also calls to /etc/*, as this would produce a real behavior blocker but for now it is better than anything in existence)

The init.d script is written for some other distribution, I will try to fix it, but for now:

> ● douane.service - SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases.
   Loaded: loaded (/etc/init.d/douane; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since čet 2017-09-21 09:59:26 CEST; 4min 39s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 28055 ExecStart=/etc/init.d/douane start (code=exited, status=127)

sep 21 09:59:26 ********* systemd[1]: Starting SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases....
sep 21 09:59:26 ********* douane[28055]: /etc/init.d/douane: line 23: log_daemon_msg: command not found
sep 21 09:59:26 ********* douane[28055]: /etc/init.d/douane: line 32: start-stop-daemon: command not found
sep 21 09:59:26 ********* douane[28055]: /etc/init.d/douane: line 33: log_end_msg: command not found
sep 21 09:59:26 ********* systemd[1]: douane.service: Control process exited, code=exited status=127
sep 21 09:59:26 ********* systemd[1]: Failed to start SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases..
sep 21 09:59:26 ********* systemd[1]: douane.service: Unit entered failed state.
sep 21 09:59:26 ********* systemd[1]: douane.service: Failed with result 'exit-code'.

**Comment by zedtux** [comment]
Hello @roker and thank you for your issue.
I like your comment, I'm open to change Douane in any better way.

Regarding your issue, as I already said in the past, I'm working on Debian, so all my developments are Debian oriented.
As of today, nobody ported it to other distributions. Please feel free to open a PR and I'll be more than happy to review it and merge it!

**Comment by intika** [comment]
fixed on current release can you try

**Comment by intika** [comment]
should be closed

**Comment by zedtux** [comment]
@roker can you please update this issue?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-daemon/issues/10).
