### ISSUE TITLE
git clone --recursive not working on GitLab

### ISSUE THREAD

**Issue by zecevicp** [Douane/douane-daemon#16]
Seems that `git clone --recursive https://gitlab.com/douaneapp/douane-daemon` is not working because in `.gitmodules` it says:
```
[submodule "dbus/interface"]
	path = dbus/interface
	url = https://github.com/Douane/douane-dbus.git
```
But that repository doesn't exist. https://gitlab.com/Douane/douane-dbus.git doesn't exist either.

**Comment by zedtux** [comment]
Nice catch @zecevicp ! Unfortunately, the name Douane was already hold by someone else, so I had to go with DouaneApp : https://gitlab.com/douaneapp.

I will update the `.gitmodules` file, thank you 👍

**Comment by zedtux** [comment]
Update done https://gitlab.com/douaneapp/douane-daemon/blob/master/.gitmodules

**Comment by zecevicp** [comment]
Thanks for the quick response. It's working now. +1

**Comment by zecevicp** [comment]
However, the same problem exists for douane-dialog

**Comment by zedtux** [comment]
Sorry about that ... I fixed it https://gitlab.com/douaneapp/douane-dialog/blob/master/.gitmodules
