### ISSUE TITLE
/etc/init.d/douane cannot start on archlinux, /lib/lsb/init-functions does not exist

### ISSUE THREAD

**Issue by solenskiner** [Douane/douane-daemon#3]
Native systemd support seems important since fedora and archlinux uses it; while debian, ubuntu and opensuse are already switching or planning to switch to systemd.

Should think about how the "Use Douane" slider communicates with init. DBus activation perhaps?

**Comment by intika** [comment]
can you try again and let us know with current init script also 
check if you have those package installed initscripts chkconfig systemd

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-daemon/issues/3).
